In [1]:
#Experiment No:5

In [2]:
# Aim : To create and manipulate array using NumPy for efficent numerical computation.

In [3]:
#Name:Mohd Mudakkir
#Roll No:41
#Subject:Data Science and Statistics
#Section:3A

In [4]:
import numpy as np

In [5]:
arr1 = np.array([10, 20, 30, 40, 50])

In [6]:
arr1

array([10, 20, 30, 40, 50])

In [8]:
arr2 =np.array([[1,2,3], [4,5,6]])

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [13]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
zeros_arr = np.zeros((3, 4))

In [15]:
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
ones_arr = np.ones((2, 5))

In [17]:
ones_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
rand_arr = np.random.rand(3, 3)

In [19]:
rand_arr

array([[0.63249705, 0.53907941, 0.86537154],
       [0.71827551, 0.56556906, 0.50445619],
       [0.85853024, 0.36748155, 0.30545192]])

In [20]:
range_arr = np.arange(10, 51, 10)

In [21]:
range_arr

array([10, 20, 30, 40, 50])